os: linux
dist: focal
language: python
python: 3.7

git:
  depth: 1

cache:
  pip: true
  directories:
    - backbone/packer/images
    - backbone/packer/builds

install:
  - pip install -e $TRAVIS_BUILD_DIR
  - mkdir ~/scratch && cd ~/scratch

jobs:
  include:
  - name: Backbone Base Image Build
    before_script:
      - sudo rm /usr/local/bin/packer
      - python3 $TRAVIS_BUILD_DIR/backbone/setup.py
    script:
      - backbone hypervisor build
      - backbone hypervisor up
      - backbone hypervisor ssh -c "echo Hello, World"

  - name: Backbone Tests
    script: backbone tests
