os: linux
dist: focal
language: python
python: 3.7

git:
  depth: 1

cache:
  pip: true
  directories:
    - backbone/packer/images
    - backbone/packer/builds

install:
  - pip install -e $TRAVIS_BUILD_DIR
  - mkdir ~/scratch && cd ~/scratch

jobs:
  include:
  - name: Backbone Base Image Build
    if: commit_message =~ travis:rebuild-image
    before_script:
      - sudo rm /usr/local/bin/packer
      - python3 $TRAVIS_BUILD_DIR/backbone/setup.py
    script:
      - sudo -E su $USER -c '~/virtualenv/python3.7/bin/backbone hypervisor build'
      - sudo -E su $USER -c '~/virtualenv/python3.7/bin/backbone hypervisor up'
      - sudo -E su $USER -c '~/virtualenv/python3.7/bin/backbone hypervisor ssh -c "echo Hello, World"'

  - name: Backbone Tests
    script: backbone tests
