os: linux
dist: bionic
language: python
python: 3.7

addons:
  apt:
    update: true
    packages:
    - cpu-checker

git:
  depth: 1

cache:
  pip: true

install:
  - git clone https://github.com/frappe/frappe --depth 1
  - pip install ./frappe
  - pip install $TRAVIS_BUILD_DIR

script:
  - backbone tests

jobs:
  include:
  - name: Backbone Setup
    script:
      - backbone hypervisor setup

  - name: Backbone Tests
    script: backbone tests
