os: linux
dist: focal
language: python
python: 3.7

git:
  depth: 1

cache:
  pip: true

install:
  - pip install $TRAVIS_BUILD_DIR
  - python3 $TRAVIS_BUILD_DIR/backbone/setup.py

jobs:
  include:
  - name: Vagrant Hello World
    script:
      - cd $TRAVIS_BUILD_DIR/backbone
      - vagrant up --provider=libvirt
      - vagrant ssh -c "echo 'Hello, World'"

  - name: Backbone Tests
    script: backbone tests
