os: linux
dist: focal
language: python
python: 3.7

git:
  depth: 1

cache:
  pip: true

install:
  - pip install $TRAVIS_BUILD_DIR

jobs:
  include:
  - name: Vagrant Hello World
    after_install: python3 $TRAVIS_BUILD_DIR/backbone/setup.py
    script:
      - cd $TRAVIS_BUILD_DIR/backbone
      - sudo -E su $USER -c 'vagrant up --provider=libvirt'
      - sudo -E su $USER -c 'vagrant ssh -c "echo \'Hello, World\'"'

  - name: Backbone Tests
    script: backbone tests
