sudo: required
dist: bionic
python: 3.7

addons:
  apt:
    update: true
    packages:
    - cpu-checker

install:
  - pip install $TRAVIS_BUILD_DIR

script:
  - backbone tests

matrix:
include:
- name: Backbone Setup
  script: 
    - backbone hypervisor setup

- name: Backbone Tests
  script: backbone tests
