---
- name: Install Ansible Docker Stack Module Dependencies
  pip:
    name:
      - pyyaml
      - jsondiff

- name: Create Registry Directory
  become: yes
  become_user: frappe
  file:
    dest: /home/frappe/registry
    state: directory

- name: Create Registry Data Directory
  become: yes
  become_user: frappe
  file:
    dest: /home/frappe/registry/data
    state: directory

- name: Create Registry Compose File
  become: yes
  become_user: frappe
  template:
    src: docker-compose.yml
    dest: /home/frappe/registry/docker-compose.yml

- name: Deploy Registry Stack
  become: yes
  become_user: frappe
  docker_stack:
    state: present
    name: registry
    compose:
      - /home/frappe/registry/docker-compose.yml

- name: Setup Registry Authentication
  become: yes
  become_user: frappe
  command: "htpasswd -Bbc registry.htpasswd {{ registry_username }} {{ registry_password }}"
  args:
    chdir: /home/frappe/registry

- name: Setup NGINX for Registry
  become: yes
  become_user: frappe
  command: /home/frappe/agent/env/bin/agent setup registry
  args:
    chdir: /home/frappe/agent
