---
- name: Create Frappe User
  user:
    name: frappe
    groups:
      - sudo
    shell: /bin/bash
    append: yes
    uid: 1000

- name: Allow Passwordless sudo Access to Frappe User
  copy:
    src: files/sudoers
    dest: /etc/sudoers.d/frappe
