---

- name: Create agent nginx hosts directory
  become: yes
  become_user: frappe
  file:
    path: /home/frappe/agent/nginx/hosts
    state: directory

- name: Create agent nginx upstream directory
  become: yes
  become_user: frappe
  file:
    path: /home/frappe/agent/nginx/upstreams
    state: directory

- name: Create nginx proxy configuration file (empty)
  become: yes
  become_user: frappe
  file:
    path: /home/frappe/agent/nginx/proxy.conf
    state: touch

- name: Symlink nginx proxy configuration
  file:
    src: /home/frappe/agent/nginx/proxy.conf
    dest: /etc/nginx/conf.d/proxy.conf
    state: link
    force: yes
    follow: no

- name: Setup agent proxy 
  become: yes
  become_user: frappe
  command: "/home/frappe/agent/env/bin/agent setup proxy --domain {{ domain }}"
  args:
    chdir: /home/frappe/agent

...
