---
- name: Setup Proxy Server
  hosts: all
  become: yes
  become_user: root
  gather_facts: no
  roles:
    - role: essentials
    - role: user
    - role: nginx
    - role: agent
    - role: proxy
    - role: node_exporter
