---
- name: Add certbot repository
  apt_repository:
   repo: 'ppa:certbot/certbot'

- name: Install essential packages
  apt: 
    state: present
    force: yes
    pkg:
      - build-essential
      - git
      - htop
      - libcrypto++-dev
      - libssl-dev
      - ntp
      - postfix
      - python3-dev
      - python3-pip
      - python-certbot-nginx
      - virtualenv
      - redis-server
      - screen
      - supervisor
      - vim
      - zlib1g-dev
   
...
